name: Chess CI

on:
  push:
    branches:
      - main
      - release/*
      - 14-setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    name: build_linux
    runs-on: ubuntu-22.04
    steps:
      - name: show dir
        run: |
          ls .
          ls ${{ github.workspace}}

      - name: configure cmake
        run: |
          mkdir ${{ github.workspace}}/build
          cmake -B ${{ github.workspace}}/build -S ${{ github.workspace}}

      # - name: build
      #   run: cmake --build ${{ github.workspace}}/build

#       - name: tests
#         run: ${{ github.workspace}}/build/all_tests

  # build_windows:
  #  name: build_windows
  #  runs-on: windows-2019
  #  steps:
  #    - name: configure cmake
  #    - name: build
  #    - name: tests
