name: Chess CI

on:
  push:
    branches:
      - main
      - release/*
      - 14-setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    name: build_linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: configure cmake
        run: |
          mkdir ${{ github.workspace}}/build
          cmake -B ${{ github.workspace}}

      - name: build
        run: cmake --build ${{ github.workspace}}/build

  test_linux:
    name: test_linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: tests
        run: |
          cd ${{ github.workspace}}/build/tests
          ./all_tests

  # test_linux:
  #   name: test_linux
  #   runs-on: ubuntu-22.04
  #   needs: build_linux
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: run tests
  #       run: ${{ github.workspace}}/build/all_tests

  # build_windows:
  #  name: build_windows
  #  runs-on: windows-2019
  #  steps:
  #    - name: configure cmake
  #    - name: build
  #    - name: tests
