name: Chess CI

on:
  push:
    branches:
      - main
      - release/*
      - 14-setup-ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    name: build_linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: configure cmake
        run: |
          mkdir ${{ github.workspace}}/build
          cmake -B ${{ github.workspace}}/build -S ${{ github.workspace}}

      - name: build
        run: cmake --build ${{ github.workspace}}/build

      - name: create build dir archive
        shell: bash
        run: |
          tar -czf build.tar.gz ${{ github.workspace}}/build

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-artifact
          path: build.tar.gz
          retention-days: 1

  test_linux:
    needs: build_linux
    name: test_linux
    runs-on: ubuntu-22.04

    steps:
      # 1. get the pre-built artifacts
      - name: Download build directory
        uses: actions/download-artifact@v4
        with:
          name: build-linux-artifact

      # 2. extract
      - name: extract build archive
        shell: bash
        run: |
          tar -xzf build.tar.gz
      # 2. test
      - name: tests
        run: |
          cd build/tests
          ./all_tests

  # test_linux:
  #   name: test_linux
  #   runs-on: ubuntu-22.04
  #   needs: build_linux
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: run tests
  #       run: ${{ github.workspace}}/build/all_tests

  # build_windows:
  #  name: build_windows
  #  runs-on: windows-2019
  #  steps:
  #    - name: configure cmake
  #    - name: build
  #    - name: tests
